# Doctrine Configuration
doctrine:
  dbal:
    driver: pdo_mysql
    charset: UTF8
    url: '%env(string:DATABASE_URL)%'
    types:
      itemIdType: Zeelo\ItemContext\Infrastructure\Item\Persistence\DBAL\ItemIdType
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    metadata_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    query_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool
    dql:
      string_functions:
        find_in_set: DoctrineExtensions\Query\Mysql\FindInSet
    mappings:
      Item:
        type: xml
        prefix: Zeelo\ItemContext\Domain\Item
        dir: '%kernel.project_dir%/src/ItemContext/Infrastructure/Item/Persistence/config'
        is_bundle: false
