version: "3.3"

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zeelo
    volumes:
      - mysql-disk:/data/db

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    working_dir: /var/www
    links:
      - php
    volumes:
      - ../:/var/www:delegated
      - ./nginx/host.conf:/etc/nginx/conf.d/host.conf

  php:
    build:
      context: ./php
    container_name: zeelo-php
    working_dir: /var/www
    links:
      - mysql
    volumes:
      - ../:/var/www:delegated
    env_file:
      - ../.env

volumes:
  mysql-disk:
